In [15]:
import statistics
import numpy as np

In [16]:
a = np.array([1])
a

array([1])

In [17]:
b = np.array([2,3])
b

array([2, 3])

In [18]:
d = a+b
d

array([3, 4])

In [19]:
b * d

array([ 6, 12])

In [20]:
b @ d

18