In [6]:
import statistics
import numpy as np

In [7]:
a = np.array([1])
a

array([1])

In [8]:
b = np.array([2,3])
b

array([2, 3])

In [9]:
c = np.array([2,3,4])
c

array([2, 3, 4])

In [10]:
a+b

array([3, 4])

In [4]:
c = np.array([2,3,4])
c

array([2, 3, 4])